export const studentsData = [
  {
    studentId: "2025001",
    firstName: "John",
    lastName: "Doe",
    dob: "2005-05-15",
    className: "12th",
    session: "2023-2024",
    division: "Science",
    additionalSkills: ["Python", "Web Development"],
    prevInstitute: "XYZ High School",
    lastGPA: 4.5,
    gender: "Male",
    parentsDetails: {
      father: {
        name: "Richard Doe",
        age: 45,
        occupation: "Engineer",
      },
      mother: {
        name: "Jane Doe",
        age: 42,
        occupation: "Teacher",
      },
    },
    payment: 12000,
    duePayment: 0,
    course: "Computer Science",
    courseFee: 12000,
    semesterFee: 6000,
    semesterFeeDue: 0,
    totalSubject: 5,
    subjectMarks: {
      Math: 90,
      Physics: 85,
      Chemistry: 88,
      Biology: 75,
      English: 92,
    },
    classTestAttend: 10,
    classTestMark: 95,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.8,
      "Sem 2": 3.9,
    },
    remarks: "Excellent student.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025002",
    firstName: "Jane",
    lastName: "Smith",
    dob: "2006-02-20",
    className: "11th",
    session: "2024-2025",
    division: "Commerce",
    additionalSkills: ["Financial Analysis", "Accounting"],
    prevInstitute: "ABC Academy",
    lastGPA: 4.2,
    gender: "Female",
    parentsDetails: {
      father: {
        name: "Robert Smith",
        age: 48,
        occupation: "Accountant",
      },
      mother: {
        name: "Mary Smith",
        age: 46,
        occupation: "Homemaker",
      },
    },
    payment: 10000,
    duePayment: 2000,
    course: "Business Studies",
    courseFee: 10000,
    semesterFee: 5000,
    semesterFeeDue: 2000,
    totalSubject: 6,
    subjectMarks: {
      Accounting: 95,
      Economics: 88,
      Statistics: 82,
      English: 90,
      Bangla: 85,
      History: 78,
    },
    classTestAttend: 9,
    classTestMark: 88,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.7,
      "Sem 2": 4.0,
    },
    remarks: "Good performance.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025003",
    firstName: "Alex",
    lastName: "Johnson",
    dob: "2005-09-03",
    className: "12th",
    session: "2023-2024",
    division: "Humanities",
    additionalSkills: ["Debate", "Creative Writing"],
    prevInstitute: "City College",
    lastGPA: 4.1,
    gender: "Male",
    parentsDetails: {
      father: {
        name: "Michael Johnson",
        age: 50,
        occupation: "Architect",
      },
      mother: {
        name: "Emily Johnson",
        age: 47,
        occupation: "Writer",
      },
    },
    payment: 9500,
    duePayment: 0,
    course: "Liberal Arts",
    courseFee: 9500,
    semesterFee: 4750,
    semesterFeeDue: 0,
    totalSubject: 4,
    subjectMarks: {
      History: 92,
      Sociology: 85,
      Philosophy: 88,
      English: 95,
    },
    classTestAttend: 10,
    classTestMark: 92,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.9,
      "Sem 2": 3.8,
    },
    remarks: "Very active in class.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025004",
    firstName: "Maria",
    lastName: "Garcia",
    dob: "2006-01-25",
    className: "11th",
    session: "2024-2025",
    division: "Science",
    additionalSkills: ["Robotics", "App Development"],
    prevInstitute: "Global School",
    lastGPA: 4.8,
    gender: "Female",
    parentsDetails: {
      father: {
        name: "Jose Garcia",
        age: 43,
        occupation: "Scientist",
      },
      mother: {
        name: "Ana Garcia",
        age: 41,
        occupation: "Doctor",
      },
    },
    payment: 12000,
    duePayment: 0,
    course: "Physics",
    courseFee: 12000,
    semesterFee: 6000,
    semesterFeeDue: 0,
    totalSubject: 5,
    subjectMarks: {
      Math: 98,
      Physics: 97,
      Chemistry: 95,
      Biology: 90,
      English: 94,
    },
    classTestAttend: 10,
    classTestMark: 99,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 4.0,
      "Sem 2": 4.0,
    },
    remarks: "Top performer in her class.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025005",
    firstName: "David",
    lastName: "Lee",
    dob: "2005-11-10",
    className: "12th",
    session: "2023-2024",
    division: "Commerce",
    additionalSkills: ["Data Analysis", "Public Speaking"],
    prevInstitute: "Greenfield Academy",
    lastGPA: 4.0,
    gender: "Male",
    parentsDetails: {
      father: {
        name: "Kenji Lee",
        age: 49,
        occupation: "Manager",
      },
      mother: {
        name: "Saki Lee",
        age: 46,
        occupation: "Graphic Designer",
      },
    },
    payment: 10000,
    duePayment: 0,
    course: "Economics",
    courseFee: 10000,
    semesterFee: 5000,
    semesterFeeDue: 0,
    totalSubject: 6,
    subjectMarks: {
      Accounting: 88,
      Economics: 92,
      Statistics: 85,
      English: 80,
      Bangla: 82,
      History: 75,
    },
    classTestAttend: 10,
    classTestMark: 85,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.7,
      "Sem 2": 3.6,
    },
    remarks: "Consistent performance.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025006",
    firstName: "Sarah",
    lastName: "Chen",
    dob: "2006-03-01",
    className: "11th",
    session: "2024-2025",
    division: "Science",
    additionalSkills: ["Bioinformatics", "Research"],
    prevInstitute: "Elite School",
    lastGPA: 4.7,
    gender: "Female",
    parentsDetails: {
      father: {
        name: "Lin Chen",
        age: 44,
        occupation: "IT Consultant",
      },
      mother: {
        name: "Wei Chen",
        age: 43,
        occupation: "Biologist",
      },
    },
    payment: 12000,
    duePayment: 12000,
    course: "Biology",
    courseFee: 12000,
    semesterFee: 6000,
    semesterFeeDue: 6000,
    totalSubject: 5,
    subjectMarks: {
      Math: 95,
      Physics: 92,
      Chemistry: 98,
      Biology: 96,
      English: 90,
    },
    classTestAttend: 10,
    classTestMark: 98,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.9,
      "Sem 2": 4.0,
    },
    remarks: "Highly motivated.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025007",
    firstName: "Omar",
    lastName: "Hassan",
    dob: "2005-07-22",
    className: "12th",
    session: "2023-2024",
    division: "Humanities",
    additionalSkills: ["Public Policy Analysis", "Debate"],
    prevInstitute: "King's Academy",
    lastGPA: 4.3,
    gender: "Male",
    parentsDetails: {
      father: {
        name: "Ahmed Hassan",
        age: 52,
        occupation: "Diplomat",
      },
      mother: {
        name: "Fatima Hassan",
        age: 48,
        occupation: "Librarian",
      },
    },
    payment: 9500,
    duePayment: 0,
    course: "Political Science",
    courseFee: 9500,
    semesterFee: 4750,
    semesterFeeDue: 0,
    totalSubject: 4,
    subjectMarks: {
      History: 95,
      Sociology: 90,
      PoliticalScience: 92,
      English: 88,
    },
    classTestAttend: 10,
    classTestMark: 94,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 4.0,
      "Sem 2": 3.9,
    },
    remarks: "Shows great leadership.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025008",
    firstName: "Liam",
    lastName: "Patel",
    dob: "2006-04-18",
    className: "11th",
    session: "2024-2025",
    division: "Commerce",
    additionalSkills: ["Digital Marketing", "Entrepreneurship"],
    prevInstitute: "Global School",
    lastGPA: 3.9,
    gender: "Male",
    parentsDetails: {
      father: {
        name: "Ajay Patel",
        age: 46,
        occupation: "Businessman",
      },
      mother: {
        name: "Priya Patel",
        age: 44,
        occupation: "Manager",
      },
    },
    payment: 10000,
    duePayment: 0,
    course: "Marketing",
    courseFee: 10000,
    semesterFee: 5000,
    semesterFeeDue: 0,
    totalSubject: 6,
    subjectMarks: {
      Accounting: 85,
      Economics: 80,
      Statistics: 78,
      English: 85,
      Bangla: 80,
      History: 75,
    },
    classTestAttend: 9,
    classTestMark: 80,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.5,
      "Sem 2": 3.7,
    },
    remarks: "Shows entrepreneurial spirit.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "2025009",
    firstName: "Chloe",
    lastName: "Evans",
    dob: "2005-08-08",
    className: "12th",
    session: "2023-2024",
    division: "Science",
    additionalSkills: ["Chemistry Research", "Data Visualization"],
    prevInstitute: "Parkside High",
    lastGPA: 4.6,
    gender: "Female",
    parentsDetails: {
      father: {
        name: "Mark Evans",
        age: 51,
        occupation: "Pharmacist",
      },
      mother: {
        name: "Lisa Evans",
        age: 49,
        occupation: "Scientist",
      },
    },
    payment: 12000,
    duePayment: 0,
    course: "Chemistry",
    courseFee: 12000,
    semesterFee: 6000,
    semesterFeeDue: 0,
    totalSubject: 5,
    subjectMarks: {
      Math: 95,
      Physics: 90,
      Chemistry: 98,
      Biology: 92,
      English: 95,
    },
    classTestAttend: 10,
    classTestMark: 97,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 4.0,
      "Sem 2": 3.9,
    },
    remarks: "Very focused on research.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
  {
    studentId: "20250010",
    firstName: "Aisha",
    lastName: "Khan",
    dob: "2006-05-28",
    className: "11th",
    session: "2024-2025",
    division: "Commerce",
    additionalSkills: ["Public Relations", "Event Management"],
    prevInstitute: "Unity School",
    lastGPA: 4.4,
    gender: "Female",
    parentsDetails: {
      father: {
        name: "Imran Khan",
        age: 47,
        occupation: "Entrepreneur",
      },
      mother: {
        name: "Zahra Khan",
        age: 45,
        occupation: "Interior Designer",
      },
    },
    payment: 10000,
    duePayment: 5000,
    course: "Business Administration",
    courseFee: 10000,
    semesterFee: 5000,
    semesterFeeDue: 5000,
    totalSubject: 6,
    subjectMarks: {
      Accounting: 90,
      Economics: 85,
      Statistics: 88,
      English: 92,
      Bangla: 80,
      History: 85,
    },
    classTestAttend: 9,
    classTestMark: 90,
    totalSemester: 4,
    perSemesterCGPA: {
      "Sem 1": 3.8,
      "Sem 2": 3.9,
    },
    remarks: "Good communication skills.",
    address: {
      vill: "Khatalbaria",
      post: "Premtoly",
      Upozila: "Godagari",
      Distric: "Rajshahi",
      Division: "Rajshahi",
      postalCode: 6280,
      holdingNo: "23/45",
    },
  },
];
